# This is a basic workflow that is manually triggered

name: Publish Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt-get update && sudo apt-get install -y gcc clang cmake
      - name: Set up osxcross
        run: |
          git clone https://github.com/tpoechtrager/osxcross.git
          cd osxcross
          mkdir -p tarballs
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.11.sdk.tar.xz -P tarballs
          UNATTENDED=yes ./build.sh
          echo "::add-path::$(pwd)/target/bin"
          echo "::add-path::$(pwd)/target/macports/pkgs/opt/local/bin"
      - name: Build Artifacts
        run: make build-darwin
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${{ github.event.inputs.version }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ github.event.inputs.version }}" \
              --generate-notes
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/logineasy
          asset_name: logineasy
 
